from __future__ import annotations

from typing import Optional, Protocol, Sequence

from src.domain.entities.nvr import NVR


class INVRRepository(Protocol):
    def add(self, nvr: NVR) -> NVR: ...
    def get_by_id(self, nvr_id: int) -> Optional[NVR]: ...
    def list_all(self) -> Sequence[NVR]: ...
    def update(self, nvr: NVR) -> NVR: ...
    def delete(self, nvr_id: int) -> None: ...
