// Generated by scripts/generate-openapi-types.mjs. Do not edit manually.

export const openApiOperations = [
  {
    "method": "get",
    "path": "/{full_path}",
    "operationId": "serve_spa__full_path__get"
  },
  {
    "method": "get",
    "path": "/api/alarms/",
    "operationId": "list_alarms_api_alarms__get"
  },
  {
    "method": "patch",
    "path": "/api/alarms/{alarm_id}",
    "operationId": "update_alarm_api_alarms__alarm_id__patch"
  },
  {
    "method": "post",
    "path": "/api/alarms/{alarm_id}/acknowledge",
    "operationId": "acknowledge_alarm_api_alarms__alarm_id__acknowledge_post"
  },
  {
    "method": "get",
    "path": "/api/alarms/{alarm_id}/evidence-manifest",
    "operationId": "get_alarm_evidence_manifest_api_alarms__alarm_id__evidence_manifest_get"
  },
  {
    "method": "get",
    "path": "/api/alarms/{alarm_id}/evidence-report",
    "operationId": "get_alarm_evidence_report_api_alarms__alarm_id__evidence_report_get"
  },
  {
    "method": "post",
    "path": "/api/alarms/{alarm_id}/false-positive",
    "operationId": "mark_alarm_false_positive_api_alarms__alarm_id__false_positive_post"
  },
  {
    "method": "post",
    "path": "/api/alarms/{alarm_id}/resolve",
    "operationId": "resolve_alarm_api_alarms__alarm_id__resolve_post"
  },
  {
    "method": "get",
    "path": "/api/alarms/{alarm_id}/snapshot",
    "operationId": "get_alarm_snapshot_api_alarms__alarm_id__snapshot_get"
  },
  {
    "method": "get",
    "path": "/api/alarms/{alarm_id}/snapshot/annotated",
    "operationId": "get_alarm_annotated_snapshot_api_alarms__alarm_id__snapshot_annotated_get"
  },
  {
    "method": "get",
    "path": "/api/alarms/camera/{camera_id}",
    "operationId": "list_camera_alarms_api_alarms_camera__camera_id__get"
  },
  {
    "method": "get",
    "path": "/api/alarms/status/{status}",
    "operationId": "list_alarms_by_status_api_alarms_status__status__get"
  },
  {
    "method": "get",
    "path": "/api/alarms/threshold-suggestions",
    "operationId": "get_threshold_suggestions_api_alarms_threshold_suggestions_get"
  },
  {
    "method": "post",
    "path": "/api/alarms/threshold-suggestions/apply",
    "operationId": "apply_threshold_suggestions_api_alarms_threshold_suggestions_apply_post"
  },
  {
    "method": "get",
    "path": "/api/alarms/training-feedback",
    "operationId": "export_training_feedback_api_alarms_training_feedback_get"
  },
  {
    "method": "get",
    "path": "/api/audit/events",
    "operationId": "list_audit_events_api_audit_events_get"
  },
  {
    "method": "post",
    "path": "/api/auth/change-password",
    "operationId": "change_password_api_auth_change_password_post"
  },
  {
    "method": "post",
    "path": "/api/auth/login",
    "operationId": "login_api_auth_login_post"
  },
  {
    "method": "post",
    "path": "/api/auth/logout",
    "operationId": "logout_api_auth_logout_post"
  },
  {
    "method": "post",
    "path": "/api/backup/system",
    "operationId": "download_system_backup_api_backup_system_post"
  },
  {
    "method": "get",
    "path": "/api/cameras/",
    "operationId": "list_cameras_api_cameras__get"
  },
  {
    "method": "post",
    "path": "/api/cameras/",
    "operationId": "add_camera_api_cameras__post"
  },
  {
    "method": "delete",
    "path": "/api/cameras/{camera_id}",
    "operationId": "delete_camera_api_cameras__camera_id__delete"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}",
    "operationId": "get_camera_api_cameras__camera_id__get"
  },
  {
    "method": "patch",
    "path": "/api/cameras/{camera_id}",
    "operationId": "update_camera_api_cameras__camera_id__patch"
  },
  {
    "method": "patch",
    "path": "/api/cameras/{camera_id}/ai",
    "operationId": "update_camera_ai_api_cameras__camera_id__ai_patch"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/analytics/person-hourly",
    "operationId": "get_camera_person_hourly_analytics_api_cameras__camera_id__analytics_person_hourly_get"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/diagnostics/health-history",
    "operationId": "diagnose_camera_health_history_api_cameras__camera_id__diagnostics_health_history_get"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/diagnostics/rtsp",
    "operationId": "diagnose_camera_rtsp_api_cameras__camera_id__diagnostics_rtsp_get"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/diagnostics/stream-history",
    "operationId": "diagnose_camera_stream_history_api_cameras__camera_id__diagnostics_stream_history_get"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/diagnostics/stream",
    "operationId": "diagnose_camera_stream_api_cameras__camera_id__diagnostics_stream_get"
  },
  {
    "method": "patch",
    "path": "/api/cameras/{camera_id}/motion",
    "operationId": "update_camera_motion_api_cameras__camera_id__motion_patch"
  },
  {
    "method": "post",
    "path": "/api/cameras/{camera_id}/ptz/home",
    "operationId": "goto_camera_ptz_home_api_cameras__camera_id__ptz_home_post"
  },
  {
    "method": "post",
    "path": "/api/cameras/{camera_id}/ptz/move",
    "operationId": "move_camera_ptz_api_cameras__camera_id__ptz_move_post"
  },
  {
    "method": "post",
    "path": "/api/cameras/{camera_id}/ptz/patrol",
    "operationId": "run_camera_ptz_patrol_api_cameras__camera_id__ptz_patrol_post"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/ptz/presets",
    "operationId": "list_camera_ptz_presets_api_cameras__camera_id__ptz_presets_get"
  },
  {
    "method": "post",
    "path": "/api/cameras/{camera_id}/ptz/presets/goto",
    "operationId": "goto_camera_ptz_preset_api_cameras__camera_id__ptz_presets_goto_post"
  },
  {
    "method": "patch",
    "path": "/api/cameras/{camera_id}/status",
    "operationId": "update_camera_status_api_cameras__camera_id__status_patch"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/stream-token",
    "operationId": "create_camera_stream_token_api_cameras__camera_id__stream_token_get"
  },
  {
    "method": "post",
    "path": "/api/cameras/bulk-add",
    "operationId": "bulk_add_cameras_api_cameras_bulk_add_post"
  },
  {
    "method": "post",
    "path": "/api/cameras/bulk-ai-settings",
    "operationId": "bulk_update_camera_ai_settings_api_cameras_bulk_ai_settings_post"
  },
  {
    "method": "post",
    "path": "/api/cameras/bulk-recording-policy",
    "operationId": "bulk_update_camera_recording_policy_api_cameras_bulk_recording_policy_post"
  },
  {
    "method": "get",
    "path": "/api/cameras/diagnostics/health-summary",
    "operationId": "diagnose_camera_health_summary_api_cameras_diagnostics_health_summary_get"
  },
  {
    "method": "post",
    "path": "/api/cameras/diagnostics/onvif-preview",
    "operationId": "preview_camera_onvif_api_cameras_diagnostics_onvif_preview_post"
  },
  {
    "method": "post",
    "path": "/api/cameras/diagnostics/rtsp-preview",
    "operationId": "preview_camera_rtsp_api_cameras_diagnostics_rtsp_preview_post"
  },
  {
    "method": "post",
    "path": "/api/cameras/scan",
    "operationId": "scan_cameras_api_cameras_scan_post"
  },
  {
    "method": "get",
    "path": "/api/health",
    "operationId": "health_check_api_health_get"
  },
  {
    "method": "get",
    "path": "/api/health/ready",
    "operationId": "readiness_check_api_health_ready_get"
  },
  {
    "method": "get",
    "path": "/api/nvrs/",
    "operationId": "list_nvrs_api_nvrs__get"
  },
  {
    "method": "post",
    "path": "/api/nvrs/",
    "operationId": "add_nvr_api_nvrs__post"
  },
  {
    "method": "delete",
    "path": "/api/nvrs/{nvr_id}",
    "operationId": "delete_nvr_api_nvrs__nvr_id__delete"
  },
  {
    "method": "get",
    "path": "/api/nvrs/{nvr_id}",
    "operationId": "get_nvr_api_nvrs__nvr_id__get"
  },
  {
    "method": "patch",
    "path": "/api/nvrs/{nvr_id}",
    "operationId": "update_nvr_api_nvrs__nvr_id__patch"
  },
  {
    "method": "post",
    "path": "/api/nvrs/{nvr_id}/import",
    "operationId": "import_nvr_cameras_api_nvrs__nvr_id__import_post"
  },
  {
    "method": "post",
    "path": "/api/nvrs/{nvr_id}/probe",
    "operationId": "probe_nvr_channels_api_nvrs__nvr_id__probe_post"
  },
  {
    "method": "post",
    "path": "/api/nvrs/{nvr_id}/probe/diagnostics",
    "operationId": "probe_nvr_channels_diagnostics_api_nvrs__nvr_id__probe_diagnostics_post"
  },
  {
    "method": "patch",
    "path": "/api/nvrs/{nvr_id}/status",
    "operationId": "update_nvr_status_api_nvrs__nvr_id__status_patch"
  },
  {
    "method": "post",
    "path": "/api/nvrs/bulk-add",
    "operationId": "bulk_add_nvrs_api_nvrs_bulk_add_post"
  },
  {
    "method": "post",
    "path": "/api/nvrs/discover",
    "operationId": "discover_nvrs_api_nvrs_discover_post"
  },
  {
    "method": "post",
    "path": "/api/nvrs/scan",
    "operationId": "scan_nvrs_api_nvrs_scan_post"
  },
  {
    "method": "get",
    "path": "/api/recordings/",
    "operationId": "list_recording_segments_api_recordings__get"
  },
  {
    "method": "get",
    "path": "/api/recordings/{segment_id}/file",
    "operationId": "get_recording_file_api_recordings__segment_id__file_get"
  },
  {
    "method": "get",
    "path": "/api/recordings/{segment_id}/metadata",
    "operationId": "get_recording_metadata_api_recordings__segment_id__metadata_get"
  },
  {
    "method": "post",
    "path": "/api/recordings/maintenance/prune",
    "operationId": "prune_recording_segments_api_recordings_maintenance_prune_post"
  },
  {
    "method": "get",
    "path": "/api/security/permissions",
    "operationId": "security_permissions_api_security_permissions_get"
  },
  {
    "method": "get",
    "path": "/api/security/posture",
    "operationId": "security_posture_api_security_posture_get"
  },
  {
    "method": "get",
    "path": "/api/setup/status",
    "operationId": "setup_status_api_setup_status_get"
  },
  {
    "method": "get",
    "path": "/api/users/",
    "operationId": "list_users_api_users__get"
  },
  {
    "method": "post",
    "path": "/api/users/",
    "operationId": "create_user_api_users__post"
  },
  {
    "method": "delete",
    "path": "/api/users/{user_id}",
    "operationId": "delete_user_api_users__user_id__delete"
  },
  {
    "method": "patch",
    "path": "/api/users/{user_id}",
    "operationId": "update_user_api_users__user_id__patch"
  }
] as const

export type OpenApiPath =
  | "/{full_path}"
  | "/api/alarms/"
  | "/api/alarms/{alarm_id}"
  | "/api/alarms/{alarm_id}/acknowledge"
  | "/api/alarms/{alarm_id}/evidence-manifest"
  | "/api/alarms/{alarm_id}/evidence-report"
  | "/api/alarms/{alarm_id}/false-positive"
  | "/api/alarms/{alarm_id}/resolve"
  | "/api/alarms/{alarm_id}/snapshot"
  | "/api/alarms/{alarm_id}/snapshot/annotated"
  | "/api/alarms/camera/{camera_id}"
  | "/api/alarms/status/{status}"
  | "/api/alarms/threshold-suggestions"
  | "/api/alarms/threshold-suggestions/apply"
  | "/api/alarms/training-feedback"
  | "/api/audit/events"
  | "/api/auth/change-password"
  | "/api/auth/login"
  | "/api/auth/logout"
  | "/api/backup/system"
  | "/api/cameras/"
  | "/api/cameras/{camera_id}"
  | "/api/cameras/{camera_id}/ai"
  | "/api/cameras/{camera_id}/analytics/person-hourly"
  | "/api/cameras/{camera_id}/diagnostics/health-history"
  | "/api/cameras/{camera_id}/diagnostics/rtsp"
  | "/api/cameras/{camera_id}/diagnostics/stream-history"
  | "/api/cameras/{camera_id}/diagnostics/stream"
  | "/api/cameras/{camera_id}/motion"
  | "/api/cameras/{camera_id}/ptz/home"
  | "/api/cameras/{camera_id}/ptz/move"
  | "/api/cameras/{camera_id}/ptz/patrol"
  | "/api/cameras/{camera_id}/ptz/presets"
  | "/api/cameras/{camera_id}/ptz/presets/goto"
  | "/api/cameras/{camera_id}/status"
  | "/api/cameras/{camera_id}/stream-token"
  | "/api/cameras/bulk-add"
  | "/api/cameras/bulk-ai-settings"
  | "/api/cameras/bulk-recording-policy"
  | "/api/cameras/diagnostics/health-summary"
  | "/api/cameras/diagnostics/onvif-preview"
  | "/api/cameras/diagnostics/rtsp-preview"
  | "/api/cameras/scan"
  | "/api/health"
  | "/api/health/ready"
  | "/api/nvrs/"
  | "/api/nvrs/{nvr_id}"
  | "/api/nvrs/{nvr_id}/import"
  | "/api/nvrs/{nvr_id}/probe"
  | "/api/nvrs/{nvr_id}/probe/diagnostics"
  | "/api/nvrs/{nvr_id}/status"
  | "/api/nvrs/bulk-add"
  | "/api/nvrs/discover"
  | "/api/nvrs/scan"
  | "/api/recordings/"
  | "/api/recordings/{segment_id}/file"
  | "/api/recordings/{segment_id}/metadata"
  | "/api/recordings/maintenance/prune"
  | "/api/security/permissions"
  | "/api/security/posture"
  | "/api/setup/status"
  | "/api/users/"
  | "/api/users/{user_id}"

export type OpenApiMethod =
  | "get"
  | "patch"
  | "post"
  | "delete"

export type OpenApiOperation =
  | { method: "get"; path: "/{full_path}"; operationId: "serve_spa__full_path__get" }
  | { method: "get"; path: "/api/alarms/"; operationId: "list_alarms_api_alarms__get" }
  | { method: "patch"; path: "/api/alarms/{alarm_id}"; operationId: "update_alarm_api_alarms__alarm_id__patch" }
  | { method: "post"; path: "/api/alarms/{alarm_id}/acknowledge"; operationId: "acknowledge_alarm_api_alarms__alarm_id__acknowledge_post" }
  | { method: "get"; path: "/api/alarms/{alarm_id}/evidence-manifest"; operationId: "get_alarm_evidence_manifest_api_alarms__alarm_id__evidence_manifest_get" }
  | { method: "get"; path: "/api/alarms/{alarm_id}/evidence-report"; operationId: "get_alarm_evidence_report_api_alarms__alarm_id__evidence_report_get" }
  | { method: "post"; path: "/api/alarms/{alarm_id}/false-positive"; operationId: "mark_alarm_false_positive_api_alarms__alarm_id__false_positive_post" }
  | { method: "post"; path: "/api/alarms/{alarm_id}/resolve"; operationId: "resolve_alarm_api_alarms__alarm_id__resolve_post" }
  | { method: "get"; path: "/api/alarms/{alarm_id}/snapshot"; operationId: "get_alarm_snapshot_api_alarms__alarm_id__snapshot_get" }
  | { method: "get"; path: "/api/alarms/{alarm_id}/snapshot/annotated"; operationId: "get_alarm_annotated_snapshot_api_alarms__alarm_id__snapshot_annotated_get" }
  | { method: "get"; path: "/api/alarms/camera/{camera_id}"; operationId: "list_camera_alarms_api_alarms_camera__camera_id__get" }
  | { method: "get"; path: "/api/alarms/status/{status}"; operationId: "list_alarms_by_status_api_alarms_status__status__get" }
  | { method: "get"; path: "/api/alarms/threshold-suggestions"; operationId: "get_threshold_suggestions_api_alarms_threshold_suggestions_get" }
  | { method: "post"; path: "/api/alarms/threshold-suggestions/apply"; operationId: "apply_threshold_suggestions_api_alarms_threshold_suggestions_apply_post" }
  | { method: "get"; path: "/api/alarms/training-feedback"; operationId: "export_training_feedback_api_alarms_training_feedback_get" }
  | { method: "get"; path: "/api/audit/events"; operationId: "list_audit_events_api_audit_events_get" }
  | { method: "post"; path: "/api/auth/change-password"; operationId: "change_password_api_auth_change_password_post" }
  | { method: "post"; path: "/api/auth/login"; operationId: "login_api_auth_login_post" }
  | { method: "post"; path: "/api/auth/logout"; operationId: "logout_api_auth_logout_post" }
  | { method: "post"; path: "/api/backup/system"; operationId: "download_system_backup_api_backup_system_post" }
  | { method: "get"; path: "/api/cameras/"; operationId: "list_cameras_api_cameras__get" }
  | { method: "post"; path: "/api/cameras/"; operationId: "add_camera_api_cameras__post" }
  | { method: "delete"; path: "/api/cameras/{camera_id}"; operationId: "delete_camera_api_cameras__camera_id__delete" }
  | { method: "get"; path: "/api/cameras/{camera_id}"; operationId: "get_camera_api_cameras__camera_id__get" }
  | { method: "patch"; path: "/api/cameras/{camera_id}"; operationId: "update_camera_api_cameras__camera_id__patch" }
  | { method: "patch"; path: "/api/cameras/{camera_id}/ai"; operationId: "update_camera_ai_api_cameras__camera_id__ai_patch" }
  | { method: "get"; path: "/api/cameras/{camera_id}/analytics/person-hourly"; operationId: "get_camera_person_hourly_analytics_api_cameras__camera_id__analytics_person_hourly_get" }
  | { method: "get"; path: "/api/cameras/{camera_id}/diagnostics/health-history"; operationId: "diagnose_camera_health_history_api_cameras__camera_id__diagnostics_health_history_get" }
  | { method: "get"; path: "/api/cameras/{camera_id}/diagnostics/rtsp"; operationId: "diagnose_camera_rtsp_api_cameras__camera_id__diagnostics_rtsp_get" }
  | { method: "get"; path: "/api/cameras/{camera_id}/diagnostics/stream-history"; operationId: "diagnose_camera_stream_history_api_cameras__camera_id__diagnostics_stream_history_get" }
  | { method: "get"; path: "/api/cameras/{camera_id}/diagnostics/stream"; operationId: "diagnose_camera_stream_api_cameras__camera_id__diagnostics_stream_get" }
  | { method: "patch"; path: "/api/cameras/{camera_id}/motion"; operationId: "update_camera_motion_api_cameras__camera_id__motion_patch" }
  | { method: "post"; path: "/api/cameras/{camera_id}/ptz/home"; operationId: "goto_camera_ptz_home_api_cameras__camera_id__ptz_home_post" }
  | { method: "post"; path: "/api/cameras/{camera_id}/ptz/move"; operationId: "move_camera_ptz_api_cameras__camera_id__ptz_move_post" }
  | { method: "post"; path: "/api/cameras/{camera_id}/ptz/patrol"; operationId: "run_camera_ptz_patrol_api_cameras__camera_id__ptz_patrol_post" }
  | { method: "get"; path: "/api/cameras/{camera_id}/ptz/presets"; operationId: "list_camera_ptz_presets_api_cameras__camera_id__ptz_presets_get" }
  | { method: "post"; path: "/api/cameras/{camera_id}/ptz/presets/goto"; operationId: "goto_camera_ptz_preset_api_cameras__camera_id__ptz_presets_goto_post" }
  | { method: "patch"; path: "/api/cameras/{camera_id}/status"; operationId: "update_camera_status_api_cameras__camera_id__status_patch" }
  | { method: "get"; path: "/api/cameras/{camera_id}/stream-token"; operationId: "create_camera_stream_token_api_cameras__camera_id__stream_token_get" }
  | { method: "post"; path: "/api/cameras/bulk-add"; operationId: "bulk_add_cameras_api_cameras_bulk_add_post" }
  | { method: "post"; path: "/api/cameras/bulk-ai-settings"; operationId: "bulk_update_camera_ai_settings_api_cameras_bulk_ai_settings_post" }
  | { method: "post"; path: "/api/cameras/bulk-recording-policy"; operationId: "bulk_update_camera_recording_policy_api_cameras_bulk_recording_policy_post" }
  | { method: "get"; path: "/api/cameras/diagnostics/health-summary"; operationId: "diagnose_camera_health_summary_api_cameras_diagnostics_health_summary_get" }
  | { method: "post"; path: "/api/cameras/diagnostics/onvif-preview"; operationId: "preview_camera_onvif_api_cameras_diagnostics_onvif_preview_post" }
  | { method: "post"; path: "/api/cameras/diagnostics/rtsp-preview"; operationId: "preview_camera_rtsp_api_cameras_diagnostics_rtsp_preview_post" }
  | { method: "post"; path: "/api/cameras/scan"; operationId: "scan_cameras_api_cameras_scan_post" }
  | { method: "get"; path: "/api/health"; operationId: "health_check_api_health_get" }
  | { method: "get"; path: "/api/health/ready"; operationId: "readiness_check_api_health_ready_get" }
  | { method: "get"; path: "/api/nvrs/"; operationId: "list_nvrs_api_nvrs__get" }
  | { method: "post"; path: "/api/nvrs/"; operationId: "add_nvr_api_nvrs__post" }
  | { method: "delete"; path: "/api/nvrs/{nvr_id}"; operationId: "delete_nvr_api_nvrs__nvr_id__delete" }
  | { method: "get"; path: "/api/nvrs/{nvr_id}"; operationId: "get_nvr_api_nvrs__nvr_id__get" }
  | { method: "patch"; path: "/api/nvrs/{nvr_id}"; operationId: "update_nvr_api_nvrs__nvr_id__patch" }
  | { method: "post"; path: "/api/nvrs/{nvr_id}/import"; operationId: "import_nvr_cameras_api_nvrs__nvr_id__import_post" }
  | { method: "post"; path: "/api/nvrs/{nvr_id}/probe"; operationId: "probe_nvr_channels_api_nvrs__nvr_id__probe_post" }
  | { method: "post"; path: "/api/nvrs/{nvr_id}/probe/diagnostics"; operationId: "probe_nvr_channels_diagnostics_api_nvrs__nvr_id__probe_diagnostics_post" }
  | { method: "patch"; path: "/api/nvrs/{nvr_id}/status"; operationId: "update_nvr_status_api_nvrs__nvr_id__status_patch" }
  | { method: "post"; path: "/api/nvrs/bulk-add"; operationId: "bulk_add_nvrs_api_nvrs_bulk_add_post" }
  | { method: "post"; path: "/api/nvrs/discover"; operationId: "discover_nvrs_api_nvrs_discover_post" }
  | { method: "post"; path: "/api/nvrs/scan"; operationId: "scan_nvrs_api_nvrs_scan_post" }
  | { method: "get"; path: "/api/recordings/"; operationId: "list_recording_segments_api_recordings__get" }
  | { method: "get"; path: "/api/recordings/{segment_id}/file"; operationId: "get_recording_file_api_recordings__segment_id__file_get" }
  | { method: "get"; path: "/api/recordings/{segment_id}/metadata"; operationId: "get_recording_metadata_api_recordings__segment_id__metadata_get" }
  | { method: "post"; path: "/api/recordings/maintenance/prune"; operationId: "prune_recording_segments_api_recordings_maintenance_prune_post" }
  | { method: "get"; path: "/api/security/permissions"; operationId: "security_permissions_api_security_permissions_get" }
  | { method: "get"; path: "/api/security/posture"; operationId: "security_posture_api_security_posture_get" }
  | { method: "get"; path: "/api/setup/status"; operationId: "setup_status_api_setup_status_get" }
  | { method: "get"; path: "/api/users/"; operationId: "list_users_api_users__get" }
  | { method: "post"; path: "/api/users/"; operationId: "create_user_api_users__post" }
  | { method: "delete"; path: "/api/users/{user_id}"; operationId: "delete_user_api_users__user_id__delete" }
  | { method: "patch"; path: "/api/users/{user_id}"; operationId: "update_user_api_users__user_id__patch" }

export type OpenApiSchemaName =
  | "AlarmEvidenceFileItem"
  | "AlarmEvidenceManifest"
  | "AlarmResolveRequest"
  | "AlarmResponse"
  | "AlarmSeverity"
  | "AlarmStatus"
  | "AlarmThresholdSuggestionApplyItem"
  | "AlarmThresholdSuggestionApplyRequest"
  | "AlarmThresholdSuggestionApplyResponse"
  | "AlarmThresholdSuggestionItem"
  | "AlarmTrainingFeedbackItem"
  | "AlarmType"
  | "AlarmUpdate"
  | "AuditEventResponse"
  | "BoundingBoxSchema"
  | "CameraBulkAiSettingsRequest"
  | "CameraBulkRecordingPolicyRequest"
  | "CameraBulkRecordingPolicyResponse"
  | "CameraCreate"
  | "CameraHealthListItemResponse"
  | "CameraHealthSampleResponse"
  | "CameraHealthSummaryResponse"
  | "CameraOnvifPreviewRequest"
  | "CameraOnvifPreviewResponse"
  | "CameraOnvifProfileInfo"
  | "CameraPageResponse"
  | "CameraPersonHourlyStatResponse"
  | "CameraPersonHourlySummaryResponse"
  | "CameraPtzGotoPresetRequest"
  | "CameraPtzGotoPresetResponse"
  | "CameraPtzHomeResponse"
  | "CameraPtzMoveRequest"
  | "CameraPtzMoveResponse"
  | "CameraPtzPatrolRequest"
  | "CameraPtzPatrolResponse"
  | "CameraPtzPresetItem"
  | "CameraPtzPresetListResponse"
  | "CameraResponse"
  | "CameraRtspDiagnostics"
  | "CameraRtspPreviewRequest"
  | "CameraScanRequest"
  | "CameraScanResult"
  | "CameraStatus"
  | "CameraStreamDiagnostics"
  | "CameraStreamMetricResponse"
  | "CameraStreamMetricSummaryResponse"
  | "CameraStreamTokenResponse"
  | "CameraUpdate"
  | "ChangePasswordRequest"
  | "HealthResponse"
  | "HTTPValidationError"
  | "LoginRequest"
  | "NVRChannelInfo"
  | "NVRCreate"
  | "NVRDiscoverResponse"
  | "NVRImportRequest"
  | "NVRPageResponse"
  | "NVRProbeDiagnostics"
  | "NVRResponse"
  | "NVRScanRequest"
  | "NVRScanResponse"
  | "NVRUpdate"
  | "ReadinessCheckResponse"
  | "ReadinessResponse"
  | "RecordingDetectionItem"
  | "RecordingMetadataResponse"
  | "RecordingMotionMetadata"
  | "RecordingPruneResponse"
  | "RecordingSegmentListResponse"
  | "RecordingSegmentResponse"
  | "SecurityPermissionsResponse"
  | "SecurityPostureFindingResponse"
  | "SecurityPostureResponse"
  | "SetupCheckResponse"
  | "SetupStatusResponse"
  | "TokenResponse"
  | "UserCreate"
  | "UserPageResponse"
  | "UserResponse"
  | "UserRole"
  | "UserUpdate"
  | "ValidationError"

export type OpenApiSchemas = {
  "AlarmEvidenceFileItem": {
    "available": boolean
    "filename"?: (string) | (null)
    "sha256"?: (string) | (null)
    "size_bytes"?: (number) | (null)
    "status": string
    "variant": string
  }
  "AlarmEvidenceManifest": {
    "acknowledged_at"?: (string) | (null)
    "alarm_id": number
    "alarm_type": OpenApiSchemas["AlarmType"]
    "bounding_box"?: (OpenApiSchemas["BoundingBoxSchema"]) | (null)
    "camera_id": number
    "confidence"?: (number) | (null)
    "created_at"?: (string) | (null)
    "false_positive": boolean
    "files": Array<OpenApiSchemas["AlarmEvidenceFileItem"]>
    "generated_at": string
    "resolved_at"?: (string) | (null)
    "severity": OpenApiSchemas["AlarmSeverity"]
    "status": OpenApiSchemas["AlarmStatus"]
  }
  "AlarmResolveRequest": {
    "false_positive"?: boolean
    "resolution_reason"?: (string) | (null)
  }
  "AlarmResponse": {
    "acknowledged_at": (string) | (null)
    "alarm_type": OpenApiSchemas["AlarmType"]
    "assigned_to"?: (string) | (null)
    "bounding_box": (OpenApiSchemas["BoundingBoxSchema"]) | (null)
    "camera_id": number
    "confidence": (number) | (null)
    "created_at": (string) | (null)
    "false_positive"?: boolean
    "id": number
    "message": (string) | (null)
    "operator_note"?: (string) | (null)
    "resolution_reason"?: (string) | (null)
    "resolved_at": (string) | (null)
    "severity"?: OpenApiSchemas["AlarmSeverity"]
    "snapshot_annotated_path"?: (string) | (null)
    "snapshot_annotated_sha256"?: (string) | (null)
    "snapshot_path": (string) | (null)
    "snapshot_sha256"?: (string) | (null)
    "status": OpenApiSchemas["AlarmStatus"]
  }
  "AlarmSeverity": "low" | "medium" | "high" | "critical"
  "AlarmStatus": "new" | "acknowledged" | "resolved"
  "AlarmThresholdSuggestionApplyItem": {
    "applied_confidence_threshold": number
    "camera_id": number
    "false_positive_rate": number
    "previous_confidence_threshold": number
    "sample_count": number
  }
  "AlarmThresholdSuggestionApplyRequest": {
    "camera_ids"?: (Array<number>) | (null)
    "limit"?: number
    "minimum_samples"?: number
  }
  "AlarmThresholdSuggestionApplyResponse": {
    "applied_count": number
    "items": Array<OpenApiSchemas["AlarmThresholdSuggestionApplyItem"]>
    "skipped_count": number
  }
  "AlarmThresholdSuggestionItem": {
    "average_confidence"?: (number) | (null)
    "camera_id": number
    "false_positive_count": number
    "false_positive_rate": number
    "recommendation": string
    "sample_count": number
    "suggested_confidence_threshold"?: (number) | (null)
  }
  "AlarmTrainingFeedbackItem": {
    "alarm_id": number
    "bounding_box": (OpenApiSchemas["BoundingBoxSchema"]) | (null)
    "camera_id": number
    "confidence": (number) | (null)
    "created_at": (string) | (null)
    "false_positive": boolean
    "operator_note"?: (string) | (null)
    "resolution_reason"?: (string) | (null)
    "severity": OpenApiSchemas["AlarmSeverity"]
    "snapshot_annotated_sha256"?: (string) | (null)
    "snapshot_sha256"?: (string) | (null)
  }
  "AlarmType": "human_detected" | "camera_offline" | "camera_health_degraded" | "motion_detected" | "person_density_anomaly"
  "AlarmUpdate": {
    "assigned_to"?: (string) | (null)
    "false_positive"?: (boolean) | (null)
    "operator_note"?: (string) | (null)
    "severity"?: (OpenApiSchemas["AlarmSeverity"]) | (null)
  }
  "AuditEventResponse": {
    "action": string
    "actor"?: (string) | (null)
    "event_hash"?: (string) | (null)
    "hash_algorithm"?: (string) | (null)
    "metadata"?: {
    [key: string]: unknown
  }
    "previous_hash"?: (string) | (null)
    "source_ip"?: (string) | (null)
    "success"?: boolean
    "timestamp": string
  }
  "BoundingBoxSchema": {
    "height": number
    "width": number
    "x": number
    "y": number
  }
  "CameraBulkAiSettingsRequest": {
    "ai_alarm_cooldown_seconds": number
    "ai_confidence_threshold": number
    "ai_frame_stride": number
    "ai_inference_width": number
    "ai_iou_threshold": number
    "camera_ids": Array<number>
  }
  "CameraBulkRecordingPolicyRequest": {
    "building"?: (string) | (null)
    "camera_ids"?: Array<number>
    "continuous_recording_enabled": boolean
    "floor"?: (string) | (null)
    "site"?: (string) | (null)
    "zone"?: (string) | (null)
  }
  "CameraBulkRecordingPolicyResponse": {
    "camera_ids": Array<number>
    "continuous_recording_enabled": boolean
    "scope": {
    [key: string]: (string) | (null)
  }
    "updated_count": number
  }
  "CameraCreate": {
    "ai_active_end"?: (string) | (null)
    "ai_active_start"?: (string) | (null)
    "ai_alarm_cooldown_seconds"?: number
    "ai_confidence_threshold"?: number
    "ai_frame_stride"?: number
    "ai_inference_width"?: number
    "ai_iou_threshold"?: number
    "ai_roi_polygon"?: (string) | (null)
    "auto_rtsp_ports"?: boolean
    "brand"?: (string) | (null)
    "building"?: (string) | (null)
    "continuous_recording_enabled"?: boolean
    "floor"?: (string) | (null)
    "host": string
    "model"?: (string) | (null)
    "motion_detection_enabled"?: boolean
    "name": string
    "onvif_port"?: (number) | (null)
    "password"?: (string) | (null)
    "rtsp_path"?: (string) | (null)
    "rtsp_port"?: (number) | (null)
    "site"?: (string) | (null)
    "username"?: (string) | (null)
    "zone"?: (string) | (null)
  }
  "CameraHealthListItemResponse": {
    "availability_percent"?: (number) | (null)
    "camera_id": number
    "health_level": string
    "health_message": string
    "latest_checked_at"?: (string) | (null)
    "latest_failure_reason"?: (string) | (null)
    "latest_latency_ms"?: (number) | (null)
    "latest_reachable"?: (boolean) | (null)
    "latest_status"?: (string) | (null)
    "reachable_count": number
    "sample_count": number
  }
  "CameraHealthSampleResponse": {
    "camera_id": number
    "checked_at": string
    "failure_reason"?: (string) | (null)
    "id": number
    "latency_ms"?: (number) | (null)
    "reachable": boolean
    "status": string
  }
  "CameraHealthSummaryResponse": {
    "availability_percent"?: (number) | (null)
    "camera_id": number
    "latest_checked_at"?: (string) | (null)
    "latest_failure_reason"?: (string) | (null)
    "latest_latency_ms"?: (number) | (null)
    "reachable_count": number
    "sample_count": number
    "samples": Array<OpenApiSchemas["CameraHealthSampleResponse"]>
    "unreachable_count": number
  }
  "CameraOnvifPreviewRequest": {
    "camera_id"?: (number) | (null)
    "host"?: (string) | (null)
    "onvif_port"?: (number) | (null)
    "password"?: (string) | (null)
    "username"?: (string) | (null)
  }
  "CameraOnvifPreviewResponse": {
    "analytics_supported"?: boolean
    "camera_id": number
    "compatibility_notes"?: Array<string>
    "event_subscription_likely"?: boolean
    "events_supported"?: boolean
    "firmware_version"?: (string) | (null)
    "first_stream_uri_masked"?: (string) | (null)
    "h264_or_h265_supported"?: boolean
    "host": string
    "imaging_supported"?: boolean
    "manufacturer"?: (string) | (null)
    "media_supported"?: boolean
    "message": string
    "model"?: (string) | (null)
    "ok": boolean
    "onvif_port": number
    "profile_count"?: number
    "profile_g_likely"?: boolean
    "profile_m_likely"?: boolean
    "profile_s_likely"?: boolean
    "profile_t_likely"?: boolean
    "profiles"?: Array<OpenApiSchemas["CameraOnvifProfileInfo"]>
    "ptz_supported"?: boolean
    "serial_number"?: (string) | (null)
    "snapshot_supported"?: boolean
    "stream_uri_count"?: number
  }
  "CameraOnvifProfileInfo": {
    "bitrate_kbps"?: (number) | (null)
    "encoding"?: (string) | (null)
    "fps"?: (number) | (null)
    "height"?: (number) | (null)
    "profile_name": string
    "profile_token": string
    "rtsp_uri_masked"?: (string) | (null)
    "snapshot_uri_masked"?: (string) | (null)
    "width"?: (number) | (null)
  }
  "CameraPageResponse": {
    "items": Array<OpenApiSchemas["CameraResponse"]>
    "page": number
    "page_size": number
    "total": number
  }
  "CameraPersonHourlyStatResponse": {
    "average_person_count": number
    "camera_id": number
    "detection_samples": number
    "first_detected_at": string
    "hour_start": string
    "id": number
    "last_detected_at": string
    "max_confidence"?: (number) | (null)
    "max_person_count": number
    "total_person_count": number
  }
  "CameraPersonHourlySummaryResponse": {
    "average_person_count_per_detection"?: (number) | (null)
    "bucket_count": number
    "buckets": Array<OpenApiSchemas["CameraPersonHourlyStatResponse"]>
    "camera_id": number
    "hours": number
    "latest_detected_at"?: (string) | (null)
    "peak_person_count": number
    "total_detection_samples": number
    "total_person_count": number
  }
  "CameraPtzGotoPresetRequest": {
    "preset_token": string
  }
  "CameraPtzGotoPresetResponse": {
    "camera_id": number
    "message": string
    "ok": boolean
    "preset_token": string
    "profile_token"?: (string) | (null)
  }
  "CameraPtzHomeResponse": {
    "camera_id": number
    "message": string
    "ok": boolean
    "profile_token"?: (string) | (null)
  }
  "CameraPtzMoveRequest": {
    "direction": "up" | "down" | "left" | "right" | "up_left" | "up_right" | "down_left" | "down_right" | "zoom_in" | "zoom_out" | "stop"
    "duration_ms"?: number
    "speed"?: number
  }
  "CameraPtzMoveResponse": {
    "camera_id": number
    "direction": string
    "message": string
    "ok": boolean
    "profile_token"?: (string) | (null)
  }
  "CameraPtzPatrolRequest": {
    "dwell_seconds"?: number
    "preset_tokens": Array<string>
  }
  "CameraPtzPatrolResponse": {
    "camera_id": number
    "message": string
    "ok": boolean
    "profile_token"?: (string) | (null)
    "visited_preset_tokens": Array<string>
  }
  "CameraPtzPresetItem": {
    "name": string
    "profile_token"?: (string) | (null)
    "token": string
  }
  "CameraPtzPresetListResponse": {
    "camera_id": number
    "presets": Array<OpenApiSchemas["CameraPtzPresetItem"]>
  }
  "CameraResponse": {
    "ai_active_end"?: (string) | (null)
    "ai_active_start"?: (string) | (null)
    "ai_alarm_cooldown_seconds": number
    "ai_confidence_threshold": number
    "ai_detection_enabled": boolean
    "ai_frame_stride": number
    "ai_inference_width": number
    "ai_iou_threshold": number
    "ai_roi_polygon"?: (string) | (null)
    "brand"?: (string) | (null)
    "building"?: (string) | (null)
    "continuous_recording_enabled"?: boolean
    "created_at"?: (string) | (null)
    "floor"?: (string) | (null)
    "host": string
    "id": number
    "model"?: (string) | (null)
    "motion_detection_enabled": boolean
    "name": string
    "nvr_id"?: (number) | (null)
    "onvif_capabilities_checked_at"?: (string) | (null)
    "onvif_port": number
    "onvif_ptz_supported"?: (boolean) | (null)
    "password_updated_at"?: (string) | (null)
    "rtsp_path": string
    "rtsp_port": number
    "site"?: (string) | (null)
    "status": OpenApiSchemas["CameraStatus"]
    "username"?: (string) | (null)
    "zone"?: (string) | (null)
  }
  "CameraRtspDiagnostics": {
    "anonymous_frame_ok": boolean
    "authenticated_frame_ok": boolean
    "authenticated_url_masked": string
    "camera_id": number
    "describe_ok": boolean
    "frame_ok": boolean
    "has_username": boolean
    "host": string
    "message": string
    "name": string
    "nvr_id"?: (number) | (null)
    "public_url": string
    "rtsp_path": string
    "rtsp_port": number
    "tcp_open": boolean
  }
  "CameraRtspPreviewRequest": {
    "camera_id"?: (number) | (null)
    "host"?: (string) | (null)
    "name"?: (string) | (null)
    "password"?: (string) | (null)
    "rtsp_path"?: (string) | (null)
    "rtsp_port"?: (number) | (null)
    "username"?: (string) | (null)
  }
  "CameraScanRequest": {
    "auto_rtsp_ports"?: boolean
    "ip_range": string
    "password"?: (string) | (null)
    "rtsp_port"?: (number) | (null)
    "username"?: (string) | (null)
  }
  "CameraScanResult": {
    "brand": string
    "desc": string
    "ip": string
    "path": string
    "port": number
    "url": string
  }
  "CameraStatus": "active" | "inactive" | "error"
  "CameraStreamDiagnostics": {
    "active_profile": string
    "ai_frame_stride": number
    "ai_inference_width": number
    "ai_provider"?: (string) | (null)
    "ai_task_running": boolean
    "average_ai_inference_ms"?: (number) | (null)
    "cached_frame_available": boolean
    "camera_id": number
    "current_broadcast_fps"?: (number) | (null)
    "failure_count": number
    "host_cpu_load_percent"?: (number) | (null)
    "host_memory_available_mb"?: (number) | (null)
    "host_memory_used_percent"?: (number) | (null)
    "last_ai_inference_ms"?: (number) | (null)
    "last_broadcast_age_seconds"?: (number) | (null)
    "last_broadcast_at"?: (string) | (null)
    "last_failure_at"?: (string) | (null)
    "last_frame_age_seconds"?: (number) | (null)
    "last_success_at"?: (string) | (null)
    "open_attempts": number
    "open_failures": number
    "open_timeout_ms": number
    "producer_running": boolean
    "producer_start_count"?: number
    "producer_started_at"?: (string) | (null)
    "producer_uptime_seconds"?: (number) | (null)
    "read_timeout_ms": number
    "reconnects"?: number
    "retry_cooldown_seconds": number
    "subscriber_count": number
    "warmup_reads": number
  }
  "CameraStreamMetricResponse": {
    "average_ai_inference_ms"?: (number) | (null)
    "camera_id": number
    "current_broadcast_fps"?: (number) | (null)
    "failure_count"?: number
    "host_cpu_load_percent"?: (number) | (null)
    "host_memory_used_percent"?: (number) | (null)
    "id": number
    "open_failures"?: number
    "producer_running": boolean
    "reconnects"?: number
    "sampled_at": string
    "subscriber_count": number
  }
  "CameraStreamMetricSummaryResponse": {
    "average_ai_inference_ms"?: (number) | (null)
    "average_broadcast_fps"?: (number) | (null)
    "average_host_cpu_load_percent"?: (number) | (null)
    "average_host_memory_used_percent"?: (number) | (null)
    "camera_id": number
    "latest_ai_inference_ms"?: (number) | (null)
    "latest_broadcast_fps"?: (number) | (null)
    "latest_sampled_at"?: (string) | (null)
    "minimum_broadcast_fps"?: (number) | (null)
    "producer_running_count": number
    "sample_count": number
    "samples": Array<OpenApiSchemas["CameraStreamMetricResponse"]>
    "total_failure_count"?: number
    "total_open_failures"?: number
    "total_reconnects"?: number
  }
  "CameraStreamTokenResponse": {
    "expires_in": number
    "stream_token": string
  }
  "CameraUpdate": {
    "ai_active_end"?: (string) | (null)
    "ai_active_start"?: (string) | (null)
    "ai_alarm_cooldown_seconds"?: (number) | (null)
    "ai_confidence_threshold"?: (number) | (null)
    "ai_frame_stride"?: (number) | (null)
    "ai_inference_width"?: (number) | (null)
    "ai_iou_threshold"?: (number) | (null)
    "ai_roi_polygon"?: (string) | (null)
    "building"?: (string) | (null)
    "continuous_recording_enabled"?: (boolean) | (null)
    "floor"?: (string) | (null)
    "host"?: (string) | (null)
    "motion_detection_enabled"?: (boolean) | (null)
    "name"?: (string) | (null)
    "onvif_port"?: (number) | (null)
    "password"?: (string) | (null)
    "rtsp_path"?: (string) | (null)
    "rtsp_port"?: (number) | (null)
    "site"?: (string) | (null)
    "username"?: (string) | (null)
    "zone"?: (string) | (null)
  }
  "ChangePasswordRequest": {
    "new_password": string
    "old_password": string
  }
  "HealthResponse": {
    "status": string
  }
  "HTTPValidationError": {
    "detail"?: Array<OpenApiSchemas["ValidationError"]>
  }
  "LoginRequest": {
    "password": string
    "username": string
  }
  "NVRChannelInfo": {
    "already_imported"?: boolean
    "bitrate_kbps"?: (number) | (null)
    "diagnostic"?: (string) | (null)
    "duplicate_reason"?: (string) | (null)
    "encoding"?: (string) | (null)
    "existing_camera_id"?: (number) | (null)
    "fps"?: (number) | (null)
    "height"?: (number) | (null)
    "import_name"?: (string) | (null)
    "manufacturer"?: (string) | (null)
    "model"?: (string) | (null)
    "profile_name": string
    "profile_token": string
    "rtsp_url": string
    "snapshot_uri"?: (string) | (null)
    "source"?: string
    "stream_role"?: (string) | (null)
    "width"?: (number) | (null)
  }
  "NVRCreate": {
    "brand"?: (string) | (null)
    "host": string
    "model"?: (string) | (null)
    "name": string
    "onvif_port"?: number
    "password"?: (string) | (null)
    "username"?: (string) | (null)
  }
  "NVRDiscoverResponse": {
    "host": string
    "port": number
    "xaddr": string
  }
  "NVRImportRequest": {
    "channels": Array<OpenApiSchemas["NVRChannelInfo"]>
  }
  "NVRPageResponse": {
    "items": Array<OpenApiSchemas["NVRResponse"]>
    "page": number
    "page_size": number
    "total": number
  }
  "NVRProbeDiagnostics": {
    "channels"?: Array<OpenApiSchemas["NVRChannelInfo"]>
    "device_manufacturer"?: (string) | (null)
    "device_model"?: (string) | (null)
    "existing_channel_count"?: number
    "fallback_error"?: (string) | (null)
    "fallback_used": boolean
    "new_channel_count"?: number
    "onvif_error"?: (string) | (null)
    "onvif_ok": boolean
    "profile_count"?: number
    "source": string
    "stream_uri_count"?: number
  }
  "NVRResponse": {
    "brand"?: (string) | (null)
    "created_at"?: (string) | (null)
    "host": string
    "id": number
    "is_active": boolean
    "model"?: (string) | (null)
    "name": string
    "onvif_port": number
    "password_updated_at"?: (string) | (null)
    "updated_at"?: (string) | (null)
    "username"?: (string) | (null)
  }
  "NVRScanRequest": {
    "ip_range": string
    "password"?: (string) | (null)
    "rtsp_port"?: (number) | (null)
    "username"?: (string) | (null)
  }
  "NVRScanResponse": {
    "brand": string
    "host": string
    "model": string
    "port": number
  }
  "NVRUpdate": {
    "host"?: (string) | (null)
    "name"?: (string) | (null)
    "onvif_port"?: (number) | (null)
    "password"?: (string) | (null)
    "username"?: (string) | (null)
  }
  "ReadinessCheckResponse": {
    "key": string
    "ok": boolean
    "severity": ("critical" | "high" | "medium" | "low" | "info") | (string)
  }
  "ReadinessResponse": {
    "blocking_issue_count": number
    "checks": Array<OpenApiSchemas["ReadinessCheckResponse"]>
    "ready": boolean
    "status": ("ready" | "degraded") | (string)
    "warning_count": number
  }
  "RecordingDetectionItem": {
    "bounding_box": OpenApiSchemas["BoundingBoxSchema"]
    "confidence": number
    "label": string
  }
  "RecordingMetadataResponse": {
    "alarm_id"?: (number) | (null)
    "camera_id": number
    "detected_at"?: (string) | (null)
    "detections": Array<OpenApiSchemas["RecordingDetectionItem"]>
    "frame_height"?: (number) | (null)
    "frame_width"?: (number) | (null)
    "motion"?: (OpenApiSchemas["RecordingMotionMetadata"]) | (null)
    "segment_id": number
  }
  "RecordingMotionMetadata": {
    "changed_percent": number
    "changed_ratio": number
  }
  "RecordingPruneResponse": {
    "deleted_db_count": number
    "quota_mb": number
    "removed_bytes": number
    "removed_count": number
    "removed_filenames": Array<string>
    "retention_days": number
    "skipped_count": number
    "skipped_reasons": Array<string>
  }
  "RecordingSegmentListResponse": {
    "items": Array<OpenApiSchemas["RecordingSegmentResponse"]>
    "limit": number
    "total": number
  }
  "RecordingSegmentResponse": {
    "alarm_id"?: (number) | (null)
    "camera_id": number
    "codec"?: (string) | (null)
    "created_at"?: (string) | (null)
    "duration_seconds"?: (number) | (null)
    "ended_at"?: (string) | (null)
    "file_sha256"?: (string) | (null)
    "filename": string
    "fps"?: (number) | (null)
    "height"?: (number) | (null)
    "id": number
    "recording_type": string
    "size_bytes"?: (number) | (null)
    "started_at": string
    "status": string
    "width"?: (number) | (null)
  }
  "SecurityPermissionsResponse": {
    "permissions": Array<string>
    "role"?: (string) | (null)
  }
  "SecurityPostureFindingResponse": {
    "message": string
    "severity": ("critical" | "high" | "medium" | "low") | (string)
  }
  "SecurityPostureResponse": {
    "active_failed_login_attempt_count": number
    "active_failed_login_key_count": number
    "alarm_report_email_configured": boolean
    "alarm_report_webhook_configured": boolean
    "app_log_json_format": boolean
    "app_log_rotation_configured": boolean
    "app_log_sensitive_query_masking": boolean
    "audit_chain_secret_configured": boolean
    "audit_webhook_configured": boolean
    "backup_external_archive_configured": boolean
    "camera_default_onvif_port_count": number
    "camera_default_rtsp_port_count": number
    "camera_encryption_key_configured": boolean
    "camera_health_critical_availability_percent": number
    "camera_health_max_latency_ms": number
    "camera_health_stale_sample_seconds": number
    "camera_health_warning_availability_percent": number
    "camera_onvif_capability_unknown_count": number
    "camera_ptz_supported_count": number
    "camera_without_password_count": number
    "content_security_policy_enabled": boolean
    "continuous_recording_excluded_camera_count": number
    "cors_origins_configured": boolean
    "device_default_onvif_port_count": number
    "device_password_rotation_compliant": boolean
    "device_password_rotation_days": number
    "device_password_total_count": number
    "device_total_count": number
    "device_without_password_count": number
    "failed_login_limit": number
    "failed_login_window_seconds": number
    "findings": Array<OpenApiSchemas["SecurityPostureFindingResponse"]>
    "https_enabled": boolean
    "jwt_secret_configured": boolean
    "max_failed_login_attempts_for_key": number
    "missing_device_password_rotation_count": number
    "nvr_default_onvif_port_count": number
    "nvr_without_password_count": number
    "overdue_camera_password_count": number
    "overdue_device_password_count": number
    "overdue_nvr_password_count": number
    "person_density_absolute_peak_person_count": number
    "person_density_alarm_cooldown_seconds": number
    "person_density_anomaly_enabled": boolean
    "person_density_baseline_multiplier": number
    "person_density_baseline_window_hours": number
    "person_density_min_baseline_buckets": number
    "person_density_min_current_peak_person_count": number
    "recording_continuous_active_end"?: (string) | (null)
    "recording_continuous_active_start"?: (string) | (null)
    "recording_continuous_enabled": boolean
    "recording_continuous_fps": number
    "recording_continuous_segment_seconds": number
    "recording_event_post_seconds": number
    "recording_event_pre_seconds": number
    "recording_max_storage_mb": number
    "recording_prune_interval_minutes": number
    "recording_retention_days": number
    "recording_storage_dir_configured": boolean
    "secure_cookie_auth": boolean
    "security_headers_enabled": boolean
    "setup_checks": Array<OpenApiSchemas["SetupCheckResponse"]>
    "status": ("hardened" | "attention") | (string)
    "stream_token_transport": string
    "stream_token_ttl_seconds": number
    "trusted_hosts_configured": boolean
  }
  "SetupCheckResponse": {
    "key": string
    "message": string
    "ok": boolean
    "severity": ("critical" | "high" | "medium" | "low" | "info") | (string)
  }
  "SetupStatusResponse": {
    "checks": Array<OpenApiSchemas["SetupCheckResponse"]>
    "ready": boolean
  }
  "TokenResponse": {
    "access_token": string
    "role": string
    "token_type"?: string
    "username": string
  }
  "UserCreate": {
    "password": string
    "role"?: OpenApiSchemas["UserRole"]
    "username": string
  }
  "UserPageResponse": {
    "items": Array<OpenApiSchemas["UserResponse"]>
    "page": number
    "page_size": number
    "total": number
  }
  "UserResponse": {
    "created_at": (string) | (null)
    "id": number
    "is_active": boolean
    "role": OpenApiSchemas["UserRole"]
    "username": string
  }
  "UserRole": "admin" | "operator" | "viewer"
  "UserUpdate": {
    "is_active"?: (boolean) | (null)
    "password"?: (string) | (null)
    "role"?: (OpenApiSchemas["UserRole"]) | (null)
  }
  "ValidationError": {
    "ctx"?: Record<string, unknown>
    "input"?: unknown
    "loc": Array<(string) | (number)>
    "msg": string
    "type": string
  }
}
