// Generated by scripts/generate-openapi-types.mjs. Do not edit manually.

export const openApiOperations = [
  {
    "method": "get",
    "path": "/{full_path}",
    "operationId": "serve_spa__full_path__get"
  },
  {
    "method": "get",
    "path": "/api/alarms/",
    "operationId": "list_alarms_api_alarms__get"
  },
  {
    "method": "patch",
    "path": "/api/alarms/{alarm_id}",
    "operationId": "update_alarm_api_alarms__alarm_id__patch"
  },
  {
    "method": "post",
    "path": "/api/alarms/{alarm_id}/acknowledge",
    "operationId": "acknowledge_alarm_api_alarms__alarm_id__acknowledge_post"
  },
  {
    "method": "get",
    "path": "/api/alarms/{alarm_id}/evidence-manifest",
    "operationId": "get_alarm_evidence_manifest_api_alarms__alarm_id__evidence_manifest_get"
  },
  {
    "method": "post",
    "path": "/api/alarms/{alarm_id}/false-positive",
    "operationId": "mark_alarm_false_positive_api_alarms__alarm_id__false_positive_post"
  },
  {
    "method": "post",
    "path": "/api/alarms/{alarm_id}/resolve",
    "operationId": "resolve_alarm_api_alarms__alarm_id__resolve_post"
  },
  {
    "method": "get",
    "path": "/api/alarms/{alarm_id}/snapshot",
    "operationId": "get_alarm_snapshot_api_alarms__alarm_id__snapshot_get"
  },
  {
    "method": "get",
    "path": "/api/alarms/{alarm_id}/snapshot/annotated",
    "operationId": "get_alarm_annotated_snapshot_api_alarms__alarm_id__snapshot_annotated_get"
  },
  {
    "method": "get",
    "path": "/api/alarms/camera/{camera_id}",
    "operationId": "list_camera_alarms_api_alarms_camera__camera_id__get"
  },
  {
    "method": "get",
    "path": "/api/alarms/status/{status}",
    "operationId": "list_alarms_by_status_api_alarms_status__status__get"
  },
  {
    "method": "get",
    "path": "/api/alarms/threshold-suggestions",
    "operationId": "get_threshold_suggestions_api_alarms_threshold_suggestions_get"
  },
  {
    "method": "post",
    "path": "/api/alarms/threshold-suggestions/apply",
    "operationId": "apply_threshold_suggestions_api_alarms_threshold_suggestions_apply_post"
  },
  {
    "method": "get",
    "path": "/api/alarms/training-feedback",
    "operationId": "export_training_feedback_api_alarms_training_feedback_get"
  },
  {
    "method": "get",
    "path": "/api/audit/events",
    "operationId": "list_audit_events_api_audit_events_get"
  },
  {
    "method": "post",
    "path": "/api/auth/change-password",
    "operationId": "change_password_api_auth_change_password_post"
  },
  {
    "method": "post",
    "path": "/api/auth/login",
    "operationId": "login_api_auth_login_post"
  },
  {
    "method": "post",
    "path": "/api/backup/system",
    "operationId": "download_system_backup_api_backup_system_post"
  },
  {
    "method": "get",
    "path": "/api/cameras/",
    "operationId": "list_cameras_api_cameras__get"
  },
  {
    "method": "post",
    "path": "/api/cameras/",
    "operationId": "add_camera_api_cameras__post"
  },
  {
    "method": "delete",
    "path": "/api/cameras/{camera_id}",
    "operationId": "delete_camera_api_cameras__camera_id__delete"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}",
    "operationId": "get_camera_api_cameras__camera_id__get"
  },
  {
    "method": "patch",
    "path": "/api/cameras/{camera_id}",
    "operationId": "update_camera_api_cameras__camera_id__patch"
  },
  {
    "method": "patch",
    "path": "/api/cameras/{camera_id}/ai",
    "operationId": "update_camera_ai_api_cameras__camera_id__ai_patch"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/diagnostics/health-history",
    "operationId": "diagnose_camera_health_history_api_cameras__camera_id__diagnostics_health_history_get"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/diagnostics/rtsp",
    "operationId": "diagnose_camera_rtsp_api_cameras__camera_id__diagnostics_rtsp_get"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/diagnostics/stream-history",
    "operationId": "diagnose_camera_stream_history_api_cameras__camera_id__diagnostics_stream_history_get"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/diagnostics/stream",
    "operationId": "diagnose_camera_stream_api_cameras__camera_id__diagnostics_stream_get"
  },
  {
    "method": "patch",
    "path": "/api/cameras/{camera_id}/status",
    "operationId": "update_camera_status_api_cameras__camera_id__status_patch"
  },
  {
    "method": "get",
    "path": "/api/cameras/{camera_id}/stream-token",
    "operationId": "create_camera_stream_token_api_cameras__camera_id__stream_token_get"
  },
  {
    "method": "post",
    "path": "/api/cameras/bulk-add",
    "operationId": "bulk_add_cameras_api_cameras_bulk_add_post"
  },
  {
    "method": "get",
    "path": "/api/cameras/diagnostics/health-summary",
    "operationId": "diagnose_camera_health_summary_api_cameras_diagnostics_health_summary_get"
  },
  {
    "method": "post",
    "path": "/api/cameras/diagnostics/onvif-preview",
    "operationId": "preview_camera_onvif_api_cameras_diagnostics_onvif_preview_post"
  },
  {
    "method": "post",
    "path": "/api/cameras/diagnostics/rtsp-preview",
    "operationId": "preview_camera_rtsp_api_cameras_diagnostics_rtsp_preview_post"
  },
  {
    "method": "post",
    "path": "/api/cameras/scan",
    "operationId": "scan_cameras_api_cameras_scan_post"
  },
  {
    "method": "get",
    "path": "/api/health",
    "operationId": "health_check_api_health_get"
  },
  {
    "method": "get",
    "path": "/api/health/ready",
    "operationId": "readiness_check_api_health_ready_get"
  },
  {
    "method": "get",
    "path": "/api/nvrs/",
    "operationId": "list_nvrs_api_nvrs__get"
  },
  {
    "method": "post",
    "path": "/api/nvrs/",
    "operationId": "add_nvr_api_nvrs__post"
  },
  {
    "method": "delete",
    "path": "/api/nvrs/{nvr_id}",
    "operationId": "delete_nvr_api_nvrs__nvr_id__delete"
  },
  {
    "method": "get",
    "path": "/api/nvrs/{nvr_id}",
    "operationId": "get_nvr_api_nvrs__nvr_id__get"
  },
  {
    "method": "patch",
    "path": "/api/nvrs/{nvr_id}",
    "operationId": "update_nvr_api_nvrs__nvr_id__patch"
  },
  {
    "method": "post",
    "path": "/api/nvrs/{nvr_id}/import",
    "operationId": "import_nvr_cameras_api_nvrs__nvr_id__import_post"
  },
  {
    "method": "post",
    "path": "/api/nvrs/{nvr_id}/probe",
    "operationId": "probe_nvr_channels_api_nvrs__nvr_id__probe_post"
  },
  {
    "method": "post",
    "path": "/api/nvrs/{nvr_id}/probe/diagnostics",
    "operationId": "probe_nvr_channels_diagnostics_api_nvrs__nvr_id__probe_diagnostics_post"
  },
  {
    "method": "patch",
    "path": "/api/nvrs/{nvr_id}/status",
    "operationId": "update_nvr_status_api_nvrs__nvr_id__status_patch"
  },
  {
    "method": "post",
    "path": "/api/nvrs/bulk-add",
    "operationId": "bulk_add_nvrs_api_nvrs_bulk_add_post"
  },
  {
    "method": "post",
    "path": "/api/nvrs/discover",
    "operationId": "discover_nvrs_api_nvrs_discover_post"
  },
  {
    "method": "post",
    "path": "/api/nvrs/scan",
    "operationId": "scan_nvrs_api_nvrs_scan_post"
  },
  {
    "method": "get",
    "path": "/api/security/permissions",
    "operationId": "security_permissions_api_security_permissions_get"
  },
  {
    "method": "get",
    "path": "/api/security/posture",
    "operationId": "security_posture_api_security_posture_get"
  },
  {
    "method": "get",
    "path": "/api/setup/status",
    "operationId": "setup_status_api_setup_status_get"
  },
  {
    "method": "get",
    "path": "/api/users/",
    "operationId": "list_users_api_users__get"
  },
  {
    "method": "post",
    "path": "/api/users/",
    "operationId": "create_user_api_users__post"
  },
  {
    "method": "delete",
    "path": "/api/users/{user_id}",
    "operationId": "delete_user_api_users__user_id__delete"
  },
  {
    "method": "patch",
    "path": "/api/users/{user_id}",
    "operationId": "update_user_api_users__user_id__patch"
  }
] as const

export type OpenApiPath =
  | "/{full_path}"
  | "/api/alarms/"
  | "/api/alarms/{alarm_id}"
  | "/api/alarms/{alarm_id}/acknowledge"
  | "/api/alarms/{alarm_id}/evidence-manifest"
  | "/api/alarms/{alarm_id}/false-positive"
  | "/api/alarms/{alarm_id}/resolve"
  | "/api/alarms/{alarm_id}/snapshot"
  | "/api/alarms/{alarm_id}/snapshot/annotated"
  | "/api/alarms/camera/{camera_id}"
  | "/api/alarms/status/{status}"
  | "/api/alarms/threshold-suggestions"
  | "/api/alarms/threshold-suggestions/apply"
  | "/api/alarms/training-feedback"
  | "/api/audit/events"
  | "/api/auth/change-password"
  | "/api/auth/login"
  | "/api/backup/system"
  | "/api/cameras/"
  | "/api/cameras/{camera_id}"
  | "/api/cameras/{camera_id}/ai"
  | "/api/cameras/{camera_id}/diagnostics/health-history"
  | "/api/cameras/{camera_id}/diagnostics/rtsp"
  | "/api/cameras/{camera_id}/diagnostics/stream-history"
  | "/api/cameras/{camera_id}/diagnostics/stream"
  | "/api/cameras/{camera_id}/status"
  | "/api/cameras/{camera_id}/stream-token"
  | "/api/cameras/bulk-add"
  | "/api/cameras/diagnostics/health-summary"
  | "/api/cameras/diagnostics/onvif-preview"
  | "/api/cameras/diagnostics/rtsp-preview"
  | "/api/cameras/scan"
  | "/api/health"
  | "/api/health/ready"
  | "/api/nvrs/"
  | "/api/nvrs/{nvr_id}"
  | "/api/nvrs/{nvr_id}/import"
  | "/api/nvrs/{nvr_id}/probe"
  | "/api/nvrs/{nvr_id}/probe/diagnostics"
  | "/api/nvrs/{nvr_id}/status"
  | "/api/nvrs/bulk-add"
  | "/api/nvrs/discover"
  | "/api/nvrs/scan"
  | "/api/security/permissions"
  | "/api/security/posture"
  | "/api/setup/status"
  | "/api/users/"
  | "/api/users/{user_id}"

export type OpenApiMethod =
  | "get"
  | "patch"
  | "post"
  | "delete"

export type OpenApiOperation =
  | { method: "get"; path: "/{full_path}"; operationId: "serve_spa__full_path__get" }
  | { method: "get"; path: "/api/alarms/"; operationId: "list_alarms_api_alarms__get" }
  | { method: "patch"; path: "/api/alarms/{alarm_id}"; operationId: "update_alarm_api_alarms__alarm_id__patch" }
  | { method: "post"; path: "/api/alarms/{alarm_id}/acknowledge"; operationId: "acknowledge_alarm_api_alarms__alarm_id__acknowledge_post" }
  | { method: "get"; path: "/api/alarms/{alarm_id}/evidence-manifest"; operationId: "get_alarm_evidence_manifest_api_alarms__alarm_id__evidence_manifest_get" }
  | { method: "post"; path: "/api/alarms/{alarm_id}/false-positive"; operationId: "mark_alarm_false_positive_api_alarms__alarm_id__false_positive_post" }
  | { method: "post"; path: "/api/alarms/{alarm_id}/resolve"; operationId: "resolve_alarm_api_alarms__alarm_id__resolve_post" }
  | { method: "get"; path: "/api/alarms/{alarm_id}/snapshot"; operationId: "get_alarm_snapshot_api_alarms__alarm_id__snapshot_get" }
  | { method: "get"; path: "/api/alarms/{alarm_id}/snapshot/annotated"; operationId: "get_alarm_annotated_snapshot_api_alarms__alarm_id__snapshot_annotated_get" }
  | { method: "get"; path: "/api/alarms/camera/{camera_id}"; operationId: "list_camera_alarms_api_alarms_camera__camera_id__get" }
  | { method: "get"; path: "/api/alarms/status/{status}"; operationId: "list_alarms_by_status_api_alarms_status__status__get" }
  | { method: "get"; path: "/api/alarms/threshold-suggestions"; operationId: "get_threshold_suggestions_api_alarms_threshold_suggestions_get" }
  | { method: "post"; path: "/api/alarms/threshold-suggestions/apply"; operationId: "apply_threshold_suggestions_api_alarms_threshold_suggestions_apply_post" }
  | { method: "get"; path: "/api/alarms/training-feedback"; operationId: "export_training_feedback_api_alarms_training_feedback_get" }
  | { method: "get"; path: "/api/audit/events"; operationId: "list_audit_events_api_audit_events_get" }
  | { method: "post"; path: "/api/auth/change-password"; operationId: "change_password_api_auth_change_password_post" }
  | { method: "post"; path: "/api/auth/login"; operationId: "login_api_auth_login_post" }
  | { method: "post"; path: "/api/backup/system"; operationId: "download_system_backup_api_backup_system_post" }
  | { method: "get"; path: "/api/cameras/"; operationId: "list_cameras_api_cameras__get" }
  | { method: "post"; path: "/api/cameras/"; operationId: "add_camera_api_cameras__post" }
  | { method: "delete"; path: "/api/cameras/{camera_id}"; operationId: "delete_camera_api_cameras__camera_id__delete" }
  | { method: "get"; path: "/api/cameras/{camera_id}"; operationId: "get_camera_api_cameras__camera_id__get" }
  | { method: "patch"; path: "/api/cameras/{camera_id}"; operationId: "update_camera_api_cameras__camera_id__patch" }
  | { method: "patch"; path: "/api/cameras/{camera_id}/ai"; operationId: "update_camera_ai_api_cameras__camera_id__ai_patch" }
  | { method: "get"; path: "/api/cameras/{camera_id}/diagnostics/health-history"; operationId: "diagnose_camera_health_history_api_cameras__camera_id__diagnostics_health_history_get" }
  | { method: "get"; path: "/api/cameras/{camera_id}/diagnostics/rtsp"; operationId: "diagnose_camera_rtsp_api_cameras__camera_id__diagnostics_rtsp_get" }
  | { method: "get"; path: "/api/cameras/{camera_id}/diagnostics/stream-history"; operationId: "diagnose_camera_stream_history_api_cameras__camera_id__diagnostics_stream_history_get" }
  | { method: "get"; path: "/api/cameras/{camera_id}/diagnostics/stream"; operationId: "diagnose_camera_stream_api_cameras__camera_id__diagnostics_stream_get" }
  | { method: "patch"; path: "/api/cameras/{camera_id}/status"; operationId: "update_camera_status_api_cameras__camera_id__status_patch" }
  | { method: "get"; path: "/api/cameras/{camera_id}/stream-token"; operationId: "create_camera_stream_token_api_cameras__camera_id__stream_token_get" }
  | { method: "post"; path: "/api/cameras/bulk-add"; operationId: "bulk_add_cameras_api_cameras_bulk_add_post" }
  | { method: "get"; path: "/api/cameras/diagnostics/health-summary"; operationId: "diagnose_camera_health_summary_api_cameras_diagnostics_health_summary_get" }
  | { method: "post"; path: "/api/cameras/diagnostics/onvif-preview"; operationId: "preview_camera_onvif_api_cameras_diagnostics_onvif_preview_post" }
  | { method: "post"; path: "/api/cameras/diagnostics/rtsp-preview"; operationId: "preview_camera_rtsp_api_cameras_diagnostics_rtsp_preview_post" }
  | { method: "post"; path: "/api/cameras/scan"; operationId: "scan_cameras_api_cameras_scan_post" }
  | { method: "get"; path: "/api/health"; operationId: "health_check_api_health_get" }
  | { method: "get"; path: "/api/health/ready"; operationId: "readiness_check_api_health_ready_get" }
  | { method: "get"; path: "/api/nvrs/"; operationId: "list_nvrs_api_nvrs__get" }
  | { method: "post"; path: "/api/nvrs/"; operationId: "add_nvr_api_nvrs__post" }
  | { method: "delete"; path: "/api/nvrs/{nvr_id}"; operationId: "delete_nvr_api_nvrs__nvr_id__delete" }
  | { method: "get"; path: "/api/nvrs/{nvr_id}"; operationId: "get_nvr_api_nvrs__nvr_id__get" }
  | { method: "patch"; path: "/api/nvrs/{nvr_id}"; operationId: "update_nvr_api_nvrs__nvr_id__patch" }
  | { method: "post"; path: "/api/nvrs/{nvr_id}/import"; operationId: "import_nvr_cameras_api_nvrs__nvr_id__import_post" }
  | { method: "post"; path: "/api/nvrs/{nvr_id}/probe"; operationId: "probe_nvr_channels_api_nvrs__nvr_id__probe_post" }
  | { method: "post"; path: "/api/nvrs/{nvr_id}/probe/diagnostics"; operationId: "probe_nvr_channels_diagnostics_api_nvrs__nvr_id__probe_diagnostics_post" }
  | { method: "patch"; path: "/api/nvrs/{nvr_id}/status"; operationId: "update_nvr_status_api_nvrs__nvr_id__status_patch" }
  | { method: "post"; path: "/api/nvrs/bulk-add"; operationId: "bulk_add_nvrs_api_nvrs_bulk_add_post" }
  | { method: "post"; path: "/api/nvrs/discover"; operationId: "discover_nvrs_api_nvrs_discover_post" }
  | { method: "post"; path: "/api/nvrs/scan"; operationId: "scan_nvrs_api_nvrs_scan_post" }
  | { method: "get"; path: "/api/security/permissions"; operationId: "security_permissions_api_security_permissions_get" }
  | { method: "get"; path: "/api/security/posture"; operationId: "security_posture_api_security_posture_get" }
  | { method: "get"; path: "/api/setup/status"; operationId: "setup_status_api_setup_status_get" }
  | { method: "get"; path: "/api/users/"; operationId: "list_users_api_users__get" }
  | { method: "post"; path: "/api/users/"; operationId: "create_user_api_users__post" }
  | { method: "delete"; path: "/api/users/{user_id}"; operationId: "delete_user_api_users__user_id__delete" }
  | { method: "patch"; path: "/api/users/{user_id}"; operationId: "update_user_api_users__user_id__patch" }
